name: Bug Report
description: Report a bug or unexpected behavior
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate.

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Microsoft Edge
        - Google Chrome
        - Chromium
        - Brave
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: 'What version of the browser are you using? (e.g., 120.0.6099.130)'
      placeholder: '120.0.6099.130'
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: 'What version of WhoRenderedThis are you using?'
      placeholder: '0.1.0'
    validations:
      required: true

  - type: input
    id: react-site
    attributes:
      label: React Site URL
      description: 'Which React website were you testing on? (if applicable)'
      placeholder: 'https://react.dev'
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "When I hover over a component, the overlay doesn't appear..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Hover over '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any errors in the browser console? (Right-click > Inspect > Console tab)
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
